services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    depends_on:
      - filebrowser
    networks:
      - share_net

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - /srv/filebrowser/data/ro:/srv/data/ro:ro
      - /srv/filebrowser/data/rw:/srv/data/rw
      - /srv/filebrowser/database:/database
      - /srv/filebrowser/config:/config
    ports:
      - "8080:80"
    networks:
      - share_net

networks:
  share_net:
    driver: bridge